# Generated by Django 6.0 on 2026-01-06 15:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_delete_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_user_id_b60ed6_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_date_ad8c94_idx',
        ),
        migrations.AddField(
            model_name='transaction',
            name='kind',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default='expense', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'date'], name='transaction_user_id_8af7f1_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category'], name='transaction_categor_e3f163_idx'),
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='place',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
    ]
